[package]
name = "rts_codegen"
version = "0.1.0"
authors = ["Ben Hansen <bhbenjaminhansen@gmail.com>"]
edition = "2018"

[dependencies]
naga = { version = "0.6", features = ['wgsl-in', 'spv-out']}
syn = "1"
quote = "1"
proc-macro2 = "1"

[dev-dependencies]
trybuild = "1"